---
title: "20230603_ExplorePSIMethods"
output: html_document
date: '2023-07-03'
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

library(tidyverse)
library(data.table)


# I use layer a lot, to rotate long x-axis labels
Rotate_x_labels <- theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```


## Intro

I want a method to get itnerpretable PSI measurements for splicing. leafcutter PSI is confounded by number of junctions in cluster, among other things.


First read junc counts

```{r}

dat <- fread("../code/SplicingAnalysis/CombinedJuncTables/All.tsv.gz")

IntronAnnotations <- read_tsv("../data/IntronAnnotationsFromYang.Updated.tsv.gz") %>%
  dplyr::rename(stop=end)



# IntronAnnotations %>%
#   filter(!str_detect(SuperAnnotation, "Noncoding")) %>%
#   mutate(ProductiveOrUnproductive)
  
dat %>%
  distinct(chrom, start, stop, strand) %>% nrow()

dat.wide <- dat %>%
  split(.$Dataset) %>%
  lapply(pivot_wider, names_from=c("Dataset", "IndID", "RepNumber"), values_from="Count", values_fill=0) %>%
  map(~mutate(.x, stop=stop+1)) %>%
  map(~inner_join(.x, IntronAnnotations))

dat.medians <- dat.wide$Expression.Splicing %>%
  filter(SuperAnnotation %in% c("AnnotatedJunc_ProductiveCodingGene")) %>%
  group_by(gene) %>%
  mutate(across(contains(".junc"), median)) %>%
  ungroup() %>%
  dplyr::select(gene, everything())

dat.medians.mat <- dat.medians %>%
  distinct(gene, .keep_all=T) %>%
  dplyr::select(gene, contains(".junc")) %>%
  column_to_rownames("gene") %>%
  as.matrix()

dat.AlmostMat <- dat.wide$Expression.Splicing %>%
  filter(gene %in% rownames(dat.medians.mat)) %>%
  dplyr::select(chrom, start, stop, strand, gene, contains(".junc")) %>%
  unite(Intron, chrom, start, stop, strand)

dat.AlmostMat.genes <- dat.AlmostMat$gene

dat.Mat <- dat.AlmostMat %>%
  dplyr::select(-gene) %>%
  column_to_rownames("Intron") %>%
  as.matrix()


dat.Normalized <- (dat.Mat / dat.medians.mat[dat.AlmostMat.genes,]) %>%
  as.data.frame() %>%
  rownames_to_column("Intron") %>%
  separate(Intron, into=c("chrom", "start", "stop", "strand"), sep='_', convert=T)
dat.Normalized[sapply(dat.Normalized, is.infinite)] <- NaN

PSI.Medians <- dat.Normalized %>%
  gather(key='sample', value='PSI', contains(".junc")) %>%
  group_by(chrom, start, stop, strand) %>%
  summarise(med = median(PSI, na.rm = T)) %>%
  ungroup() %>%
  inner_join(IntronAnnotations)

PSI.Medians %>%
  dplyr::select(med, SuperAnnotation, SemiSupergroupAnnotations) %>%
  ggplot(aes(x=med, color=SuperAnnotation)) +
  geom_vline(xintercept=0) +
  stat_ecdf() +
  coord_cartesian(xlim=c(0.001, 100)) +
  scale_x_continuous(trans='log10') +
  facet_wrap(~SemiSupergroupAnnotations) +
  theme_bw()

PSI.Medians %>%
  dplyr::select(med, SuperAnnotation, SemiSupergroupAnnotations) %>%
  ggplot(aes(x=med, color=SuperAnnotation)) +
  geom_vline(xintercept=1) +
  stat_ecdf() +
  coord_cartesian(xlim=c(0.001, 100)) +
  scale_x_continuous(trans='log10') +
  theme_bw() +
  labs(y="ecdf", x="JuncCount / MedianProductiveJuncCountInHostGene")

PSI.Medians %>%
  dplyr::select(med, SuperAnnotation, SemiSupergroupAnnotations) %>%
  mutate(med = pmin(med, 1)) %>%
  ggplot(aes(x=med, color=SuperAnnotation)) +
  geom_vline(xintercept=1) +
  stat_ecdf() +
  coord_cartesian(xlim=c(0.001, 100)) +
  scale_x_continuous(trans='log10') +
  theme_bw()




```

Ok so now that I have a method to transform the data into this PSI proxy, let's write a function so I can reasonably efficiently do this.

```{r}

ClusteredIntrons <- fread("../code/SplicingAnalysis/leafcutter/clustering/autosomes/leafcutter_perind_numers.counts.gz", select=1, col.names=c("Intron")) %>%
  separate(Intron, into=c("chrom", "start", "stop", "cluster"), convert=T, remove=F, sep=":") %>%
  mutate(strand = str_extract(cluster, "[+-]$")) %>%
  mutate(cluster = str_remove(cluster, "_[+-]$"))

IntronNames <- IntronAnnotations %>%
  dplyr::select(chrom:strand) %>%
  left_join(ClusteredIntrons) %>%
  mutate(NewChrom = str_remove(chrom, "^chr")) %>%
  mutate(name = case_when(
    is.na(cluster) ~ str_glue("{NewChrom}:{start}:{stop}:clu_NA_{strand}"),
    TRUE ~ str_glue("{NewChrom}:{start}:{stop}:{cluster}_{strand}")
  )) %>%
  dplyr::select(chrom, start, stop, strand, name, cluster)



test.dat <- dat.wide$chRNA.Expression.Splicing %>% head(10000)

TransformTo_RatioFromMedianProductive <- function(df){
  dat.medians <- df %>%
    filter(SuperAnnotation %in% c("AnnotatedJunc_ProductiveCodingGene")) %>%
    group_by(gene) %>%
    mutate(across(contains(".junc"), median)) %>%
    ungroup() %>%
    dplyr::select(gene, everything())
  dat.medians.mat <- dat.medians %>%
    distinct(gene, .keep_all=T) %>%
    dplyr::select(gene, contains(".junc")) %>%
    column_to_rownames("gene") %>%
    as.matrix()
  dat.AlmostMat <- df %>%
    filter(gene %in% rownames(dat.medians.mat)) %>%
    dplyr::select(chrom, start, stop, strand, gene, contains(".junc")) %>%
    unite(Intron, chrom, start, stop, strand)
  dat.AlmostMat.genes <- dat.AlmostMat$gene
  dat.Mat <- dat.AlmostMat %>%
    dplyr::select(-gene) %>%
    column_to_rownames("Intron") %>%
    as.matrix()
  df.out <- (dat.Mat / dat.medians.mat[dat.AlmostMat.genes,]) %>%
    as.data.frame() %>%
    rownames_to_column("Intron") %>%
    separate(Intron, into=c("chrom", "start", "stop", "strand"), sep='_', convert=T) %>%
    inner_join(IntronNames) %>%
    mutate(score = ".") %>%
    dplyr::select(chrom, start, stop, name, score, strand, contains(".junc"))
  df.out[sapply(df.out, is.infinite)] <- NaN
  
    return(df.out)
}


TransformTo_RatioFromMaxInCluster <- function(df){
    Count.Table.mat <- df %>%
    dplyr::select(chrom:strand, contains(".junc")) %>%
    left_join(IntronNames) %>%
    filter(!is.na(cluster)) %>%
    unite(Intron, chrom, start, stop, strand, cluster, sep=":") %>%
    dplyr::select(Intron, contains(".junc")) %>%
    column_to_rownames("Intron") %>%
    as.matrix()
  ClusterMax.mat <- Count.Table.mat %>%
      as.data.frame() %>%
      rownames_to_column("junc") %>%
      mutate(cluster=str_replace(junc, "^.+?:.+?:.+?:.+?:(.+)$", "\\1")) %>%
      group_by(cluster) %>%
      mutate(across(where(is.numeric), max)) %>%
      ungroup() %>%
      select(junc, everything(), -cluster) %>%
      column_to_rownames("junc") %>%
      as.matrix()
  df.out <- ((Count.Table.mat / ClusterMax.mat)) %>%
    as.data.frame() %>%
    rownames_to_column("Intron") %>%
    separate(Intron, into=c("chrom", "start", "stop", "strand", "cluster"), sep=":", convert=T) %>%
    dplyr::select(-cluster) %>%
    inner_join(IntronNames) %>%
    mutate(score = ".") %>%
    dplyr::select(chrom, start, stop, name, score, strand, contains(".junc"))
  return(df.out)
}

TransformTo_RatioFromClusterTotal <- function(df){
    Count.Table.mat <- df %>%
    dplyr::select(chrom:strand, contains(".junc")) %>%
    left_join(IntronNames) %>%
    filter(!is.na(cluster)) %>%
    unite(Intron, chrom, start, stop, strand, cluster, sep=":") %>%
    dplyr::select(Intron, contains(".junc")) %>%
    column_to_rownames("Intron") %>%
    as.matrix()
  ClusterMax.mat <- Count.Table.mat %>%
      as.data.frame() %>%
      rownames_to_column("junc") %>%
      mutate(cluster=str_replace(junc, "^.+?:.+?:.+?:.+?:(.+)$", "\\1")) %>%
      group_by(cluster) %>%
      mutate(across(where(is.numeric), sum)) %>%
      ungroup() %>%
      select(junc, everything(), -cluster) %>%
      column_to_rownames("junc") %>%
      as.matrix()
  df.out <- ((Count.Table.mat / ClusterMax.mat)) %>%
    as.data.frame() %>%
    rownames_to_column("Intron") %>%
    separate(Intron, into=c("chrom", "start", "stop", "strand", "cluster"), sep=":", convert=T) %>%
    dplyr::select(-cluster) %>%
    inner_join(IntronNames) %>%
    mutate(score = ".") %>%
    dplyr::select(chrom, start, stop, name, score, strand, contains(".junc"))
  return(df.out)
}

results.FromMed <- TransformTo_RatioFromMedianProductive(test.dat)

results.FromSum  <- TransformTo_RatioFromClusterTotal(test.dat)

results.FromMax <- TransformTo_RatioFromMaxInCluster(test.dat)

CompareMetrics <- bind_rows(
  "Median" = results.FromMed,
  "Max" = results.FromMax,
  "Sum" = results.FromSum,
  .id = "Source"
) %>%
  dplyr::select(Source:chRNA.Expression.Splicing_NA18853_1.junc) %>%
  pivot_wider(names_from="Source", values_from="chRNA.Expression.Splicing_NA18853_1.junc")

ggplot(CompareMetrics, aes(x=Sum, y=Max)) +
  geom_point(alpha=0.2) +
  geom_abline(color='red', slope=1, intercept=0) +
  scale_y_continuous(trans='log10') +
  scale_x_continuous(trans='log10')

ggplot(CompareMetrics, aes(x=Sum, y=Median)) +
  geom_point(alpha=0.2) +
  geom_abline(color='red', slope=1, intercept=0) +
  scale_y_continuous(trans='log10', limits=c(.01,1)) +
  scale_x_continuous(trans='log10', limits=c(.01,1))

ggplot(CompareMetrics, aes(x=Max, y=Median)) +
  geom_point(alpha=0.2) +
  geom_abline(color='red', slope=1, intercept=0) +
  scale_y_continuous(trans='log10', limits=c(.01,10)) +
  scale_x_continuous(trans='log10', limits=c(.01,10))

```

